"""Dashboard-facing Python contracts shared across API, artifacts, and frontend generation."""

from .dashboard import (
    DashboardHypothesis,
    DashboardHypothesisContent,
    DashboardIslandState,
    DashboardOrigin,
    DashboardResearchPlan,
    DashboardReviewBundle,
    DashboardReviewEntry,
    DashboardReviewGate,
    DashboardReviewSection,
    DashboardRoutingArtifacts,
    DashboardSnapshot,
    DashboardState,
    GraphSeed,
    GraphSeedEdge,
    GraphSeedIsland,
    GraphSeedIslandMetrics,
    GraphSeedNode,
    InsightSection,
    MetricItem,
    PipelineStage,
    RankingItem,
    RunProgress,
    RunSummary,
)
from .snapshot_projection import build_dashboard_snapshot, build_empty_dashboard_snapshot


__all__ = [
    "DashboardHypothesis",
    "DashboardHypothesisContent",
    "DashboardIslandState",
    "DashboardOrigin",
    "DashboardResearchPlan",
    "DashboardReviewBundle",
    "DashboardReviewEntry",
    "DashboardReviewGate",
    "DashboardReviewSection",
    "DashboardRoutingArtifacts",
    "DashboardSnapshot",
    "DashboardState",
    "GraphSeed",
    "GraphSeedEdge",
    "GraphSeedIsland",
    "GraphSeedIslandMetrics",
    "GraphSeedNode",
    "InsightSection",
    "MetricItem",
    "PipelineStage",
    "RankingItem",
    "RunProgress",
    "RunSummary",
    "build_dashboard_snapshot",
    "build_empty_dashboard_snapshot",
]
