"""Host-neutral support helpers shared by host-agent tools and artifact writers."""

from .formatting import (
    format_bullet_list,
    format_hypothesis,
    format_hypothesis_with_review,
    format_meta_review_context,
    format_research_plan_context,
    format_review,
)
from .parsing import populate_result_from_metadata, validate_structured_metadata
from .pipeline_semantics import (
    PIPELINE_SKILLS,
    PIPELINE_STAGE_ALIASES,
    PIPELINE_STAGE_BOOTSTRAP,
    PIPELINE_STAGE_COMPLETED,
    PIPELINE_STAGE_CONFIGURATION,
    PIPELINE_STAGE_EVOLUTION,
    PIPELINE_STAGE_FAILED,
    PIPELINE_STAGE_GENERATION,
    PIPELINE_STAGE_IDLE,
    PIPELINE_STAGE_INSIGHTS,
    PIPELINE_STAGE_PROXIMITY,
    PIPELINE_STAGE_RANKING,
    PIPELINE_STAGE_REFLECTION,
    PIPELINE_STAGE_RESEARCH_OVERVIEW,
    PIPELINE_STAGE_TO_SKILL,
    PIPELINE_STAGES,
    TRACKED_PIPELINE_STAGES,
    canonicalize_pipeline_stage,
    current_phase_from_stage_trail,
    is_known_pipeline_skill,
    is_valid_pipeline_stage,
    load_completed_skills_from_pipeline_state_payload,
    load_stage_trail_from_current_stage_payload,
    normalize_pipeline_stage,
    normalize_stage_trail,
    record_completed_skill,
    skill_for_stage,
    update_stage_trail,
)
from .policy_runtime import (
    DEFAULT_ALLOWED_GENERATION_STRATEGIES,
    DEFAULT_ALLOWED_REVIEW_MODES,
    build_policy_decision,
    build_run_policy_from_config,
)
from .resolved_config import PROFILE_DEFAULTS, resolve_run_config, validate_resolved_config_bounds
from .strategy_router import build_strategy_decision_record, build_strategy_plan


__all__ = [
    "DEFAULT_ALLOWED_GENERATION_STRATEGIES",
    "DEFAULT_ALLOWED_REVIEW_MODES",
    "PIPELINE_SKILLS",
    "PIPELINE_STAGES",
    "PIPELINE_STAGE_ALIASES",
    "PIPELINE_STAGE_BOOTSTRAP",
    "PIPELINE_STAGE_COMPLETED",
    "PIPELINE_STAGE_CONFIGURATION",
    "PIPELINE_STAGE_EVOLUTION",
    "PIPELINE_STAGE_FAILED",
    "PIPELINE_STAGE_GENERATION",
    "PIPELINE_STAGE_IDLE",
    "PIPELINE_STAGE_INSIGHTS",
    "PIPELINE_STAGE_PROXIMITY",
    "PIPELINE_STAGE_RANKING",
    "PIPELINE_STAGE_REFLECTION",
    "PIPELINE_STAGE_RESEARCH_OVERVIEW",
    "PIPELINE_STAGE_TO_SKILL",
    "PROFILE_DEFAULTS",
    "TRACKED_PIPELINE_STAGES",
    "build_policy_decision",
    "build_run_policy_from_config",
    "build_strategy_decision_record",
    "build_strategy_plan",
    "canonicalize_pipeline_stage",
    "current_phase_from_stage_trail",
    "format_bullet_list",
    "format_hypothesis",
    "format_hypothesis_with_review",
    "format_meta_review_context",
    "format_research_plan_context",
    "format_review",
    "is_known_pipeline_skill",
    "is_valid_pipeline_stage",
    "load_completed_skills_from_pipeline_state_payload",
    "load_stage_trail_from_current_stage_payload",
    "normalize_pipeline_stage",
    "normalize_stage_trail",
    "populate_result_from_metadata",
    "record_completed_skill",
    "resolve_run_config",
    "skill_for_stage",
    "update_stage_trail",
    "validate_resolved_config_bounds",
    "validate_structured_metadata",
]
